---
- name: Installing the packages
  hosts: all
  remote_user: root
  become: true
  tasks:
     - name: Install docker and docker-compose
       script: sh install_docker.sh 

     - name: Install kong and konga
       script: sh install_kong.sh
