---
- name: Installing the packages
  hosts: all
  remote_user: newuser
  become: true
  tasks:
     - name: Install docker and docker-compose
       script: ./install_docker.sh 

     - name: Install kong and konga
       script: ./install_kong.sh
